module.exports = {
  Movies: [
    "All",
    "Action",
    "Comedy",
    "Drama",
    "Fantasy",
    "Horror",
    "Mystery",
    "Romance",
    "Documentary",
    "Exotic",
    "Other",
  ],
  Games: [
    "All",
    "FPS",
    "RTS",
    "RPG",
    "MOBA",
    "Sandbox",
    "Simulation",
    "Sports",
    "Party & Puzzles",
    "Survival & Horror",
    "Other",
  ],
  "TV Series": [
    "All",
    "Drama",
    "Sitcom",
    "Reality TV",
    "Game Show",
    "Animated Series",
    "TV Documentaries",
    "Other",
  ],
  Animes: [
    "All",
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Magic",
    "Horror",
    "Sci-Fi",
    "Romance",
    "Mystery",
    "Other",
  ],
  Restaurants: [
    "All",
    "Fine Dining",
    "Casual Dining",
    "Family Style",
    "Fast Casual",
    "Fast Food",
    "Cafe",
    "Buffet",
    "Exotic",
    "Other",
  ],
  "Tourist Sites": [
    "All",
    "Asia",
    "Africa",
    "Europe",
    "North America",
    "South America",
    "Oceania",
    "Antarctica",
    "Other",
  ],
  Schools: [
    "All",
    "Kindergarten",
    "Elementary School",
    "Middle School",
    "Public High School",
    "Private High School",
    "Public University",
    "Private University",
    "Other",
  ],
  Phones: [
    "All",
    "Apple",
    "Samsung",
    "Google",
    "Huawei",
    "Xiaomi",
    "Oppo",
    "Vivo",
    "Motorola",
    "LENOVO",
    "LG",
    "Nokia",
    "Other",
  ],
  Cars: [
    "All",
    "Sedan",
    "Coupe",
    "Sports Car",
    "Station Wagon",
    "Hatch Back",
    "Convertible",
    "SUV",
    "Minivan",
    "Pickup Truck",
    "Other",
  ],
};
